services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
